import Link from 'next/link'
import './globals.css'

import LoginBtn from './LoginBtn'
import LogOutBtn from './LogOutBtn'
import {getServerSession,} from 'next-auth'
import {authOptions} from "@/pages/api/auth/[...nextauth].js"
import { userAgent } from 'next/server'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session= await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en">
      <body>
        <div className="navbar"> 
          <Link href="/" className="logo">Appleforum</Link> 
          <Link href="/list">List</Link> 
          { 
          session 
            ? <span>{session.user.name} <LogOutBtn/> </span> 
            : <LoginBtn></LoginBtn>
          }
        </div>  
        {children}
      </body>
    </html>
  )
}
